POST http://localhost:8000/usuarios/createuser
Content-Type: application/json

{
  "nombre": "Socorro",
  "apellido_1": "Carnero",
  "apellido_2": "Centeno",
  "password": "Tecnoduero2024*",
  "username": "carnerocentenos",
  "tipo_usuario": 0
}
