POST http://localhost:8000/usuarios/createuser
Content-Type: application/json

{
  "nombre": "Miren",
  "apellido_1": "Otazu",
  "apellido_2": "Extramiana",
  "password": "MirenMeQuiere",
  "username": "motazu72",
  "tipo_usuario": 0
}
